version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - frontend

  frontend:
    build: ./web-ui
    ports:
      - "5173:5173"
    volumes:
      - ./web-ui:/app
    stdin_open: true
    tty: true
